class values:
    welskip = "com.hubbell.chargecenter:id/tvSkip"
    welname = "com.hubbell.chargecenter:id/etFirstName"
    welemail = "com.hubbell.chargecenter:id/etEmailId"
    welcode = "com.hubbell.chargecenter:id/etPhoneCode"
    welphno = "com.hubbell.chargecenter:id/etPhone"
    welcabtn = "com.hubbell.chargecenter:id/btnContinue"
    wellogin = "com.hubbell.chargecenter:id/tvAlreadyRegistered"
    logemail = "com.hubbell.chargecenter:id/etAlreadyRegisteredEmailId"
    logcode = "com.hubbell.chargecenter:id/etAlreadyRegisteredPhoneCode"
    logphno = "com.hubbell.chargecenter:id/etAlreadyRegisteredPhone"
    logbtn = "com.hubbell.chargecenter:id/btnContinueExistingUser"
    logalert = "android:id/button1"
    logotp1 = "com.hubbell.chargecenter:id/etOtpOne"
    logotp2 = "com.hubbell.chargecenter:id/etOtpTwo"
    logotp3 = "com.hubbell.chargecenter:id/etOtpThree"
    logotp4 = "com.hubbell.chargecenter:id/etOtpFour"
    logver = "com.hubbell.chargecenter:id/buttonVerify"
    loggpay = "com.hubbell.chargecenter:id/btnSaveToPhone"
    logcract = "com.hubbell.chargecenter:id/tvNewUser"
    logalert = "android:id/button1"

class home:
    homnot = "com.hubbell.chargecenter:id/ivNotification"
    homnotbk = "com.hubbell.chargecenter:id/ivBackNotification"
    homnavcard = "com.hubbell.chargecenter:id/navigation_bar_item_icon_view"
    homhelp = "com.hubbell.chargecenter:id/ivHelpAndFeedback"
    homfb = "com.hubbell.chargecenter:id/tvprovidefeedback"
    homfbsub = "com.hubbell.chargecenter:id/etsubject"
    homfbcomm = "com.hubbell.chargecenter:id/etfeedbackSubmit"
    homfbsubm = "com.hubbell.chargecenter:id/btnSubmitFeedback"
    homfbthnk = "com.hubbell.chargecenter:id/ivCancelsubmittedfeedback"
    homfbbk = "com.hubbell.chargecenter:id/ivBackHelpArticles"
    homnavacct = "com.hubbell.chargecenter:id/navigation_account"
    hompr = "com.hubbell.chargecenter:id/rlProfileNew"
    homprna = "com.hubbell.chargecenter:id/et_firstName"
    homprbk = "com.hubbell.chargecenter:id/ivBackProfile"
    homlogout = "com.hubbell.chargecenter:id/btn_logout"
    homlogoutalrt = "android:id/button1"
    hompractrn = "com.hubbell.chargecenter:id/tvViewAll"
    homprtrnbk = "com.hubbell.chargecenter:id/ivBackTransaction"
    homprteco = "com.hubbell.chargecenter:id/rlTermsandConditions"
    homprtecobk = "com.hubbell.chargecenter:id/ivBackContactSupport"

class invalid:
    invaltoast = "hierarchy/android.widget.Toast"


